package com.demo.web.admin.model.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStation<M extends BaseStation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setOperatorCode(java.lang.String operatorCode) {
		set("operatorCode", operatorCode);
	}

	public java.lang.String getOperatorCode() {
		return get("operatorCode");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPayType(java.lang.String payType) {
		set("payType", payType);
	}

	public java.lang.String getPayType() {
		return get("payType");
	}

	public void setElectricity(java.lang.String electricity) {
		set("electricity", electricity);
	}

	public java.lang.String getElectricity() {
		return get("electricity");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}

	public java.lang.String getArea() {
		return get("area");
	}

	public void setLastPay(java.lang.String lastPay) {
		set("lastPay", lastPay);
	}

	public java.lang.String getLastPay() {
		return get("lastPay");
	}

	public void setEndPay(java.lang.String endPay) {
		set("endPay", endPay);
	}

	public java.lang.String getEndPay() {
		return get("endPay");
	}

	public void setTransferName(java.lang.String transferName) {
		set("transferName", transferName);
	}

	public java.lang.String getTransferName() {
		return get("transferName");
	}

	public void setTransferBank(java.lang.String transferBank) {
		set("transferBank", transferBank);
	}

	public java.lang.String getTransferBank() {
		return get("transferBank");
	}

	public void setTransferCount(java.lang.String transferCount) {
		set("transferCount", transferCount);
	}

	public java.lang.String getTransferCount() {
		return get("transferCount");
	}

	public void setContractCode(java.lang.String contractCode) {
		set("contractCode", contractCode);
	}

	public java.lang.String getContractCode() {
		return get("contractCode");
	}

	public void setContractStart(java.lang.String contractStart) {
		set("contractStart", contractStart);
	}

	public java.lang.String getContractStart() {
		return get("contractStart");
	}

	public void setContractEnd(java.lang.String contractEnd) {
		set("contractEnd", contractEnd);
	}

	public java.lang.String getContractEnd() {
		return get("contractEnd");
	}

	public void setContractA(java.lang.String contractA) {
		set("contractA", contractA);
	}

	public java.lang.String getContractA() {
		return get("contractA");
	}

	public void setContactMan(java.lang.String contactMan) {
		set("contactMan", contactMan);
	}

	public java.lang.String getContactMan() {
		return get("contactMan");
	}

	public void setContactTelephone(java.lang.String contactTelephone) {
		set("contactTelephone", contactTelephone);
	}

	public java.lang.String getContactTelephone() {
		return get("contactTelephone");
	}

	public void setPrice(java.lang.String price) {
		set("price", price);
	}

	public java.lang.String getPrice() {
		return get("price");
	}

	public void setPayCircle(java.lang.String payCircle) {
		set("payCircle", payCircle);
	}

	public java.lang.String getPayCircle() {
		return get("payCircle");
	}

	public void setRenewMan(java.lang.String renewMan) {
		set("renewMan", renewMan);
	}

	public java.lang.String getRenewMan() {
		return get("renewMan");
	}

	public void setTicketMan(java.lang.String ticketMan) {
		set("ticketMan", ticketMan);
	}

	public java.lang.String getTicketMan() {
		return get("ticketMan");
	}

	public void setTicketTime(java.lang.String ticketTime) {
		set("ticketTime", ticketTime);
	}

	public java.lang.String getTicketTime() {
		return get("ticketTime");
	}

	public void setRename(java.lang.String rename) {
		set("rename", rename);
	}

	public java.lang.String getRename() {
		return get("rename");
	}

	public void setTurnover(java.lang.String turnover) {
		set("turnover", turnover);
	}

	public java.lang.String getTurnover() {
		return get("turnover");
	}

	public void setCtconfirm(java.lang.String ctconfirm) {
		set("ctconfirm", ctconfirm);
	}

	public java.lang.String getCtconfirm() {
		return get("ctconfirm");
	}

	public void setBaseName(java.lang.String baseName) {
		set("baseName", baseName);
	}

	public java.lang.String getBaseName() {
		return get("baseName");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
